
#include <Module/nString.h>
#include <Module/nStringAry.h>
#include <stdio.h>

int
main(int argc, char const* argv[])
{
  Func_t Debugging[] = { (Func_t)String_Constructor_Chs,
                         (Func_t)String_Constructor_Wcs,
                         (Func_t)String_Constructor_Str,
                         (Func_t)String_Constructor_Strp,
                         (Func_t)String_Destructor,
                         (Func_t)String_Join,
                         (Func_t)String_Append,
                         (Func_t)String_SubString,
                         (Func_t)String_Loop,
                         (Func_t)String_Split,
                         (Func_t)String_Compare,
                         (Func_t)String_Trim,
                         (Func_t)String_Contains,
                         (Func_t)String_Count,
                         (Func_t)String_Get,
                         (Func_t)String_Set,
                         (Func_t)String_Length,
                         (Func_t)String_ToLower,
                         (Func_t)String_ToUpper,
                         (Func_t)String_IndexOf,
                         (Func_t)String_IndexAt,
                         (Func_t)String_IndexFor,
                         (Func_t)String_LastOfIndex,
                         (Func_t)String_Replace,
                         (Func_t)String_ReplaceFor,
                         (Func_t)String_ReplaceAll,
                         (Func_t)String_Left,
                         (Func_t)String_Right,
                         (Func_t)String_Middle,
                         (Func_t)String_Extract,
                         (Func_t)String_Reverse,
                         (Func_t)String_Search,
                         (Func_t)String_IsAlpha,
                         (Func_t)String_IsLower,
                         (Func_t)String_IsUpper,
                         (Func_t)String_IsDecimal,
                         (Func_t)String_IsDigit,
                         (Func_t)String_IsSpace,
                         (Func_t)String_IsAlphaDigit,
                         (Func_t)String_IsHex,
                         (Func_t)String_IsControl,
                         (Func_t)String_IsOctal,
                         (Func_t)String_IsBinary,
                         (Func_t)String_Format,
                         (Func_t)String_Pattern,
                         (Func_t)String_Check,
                         (Func_t)String_Notation,
                         (Func_t)String_FileAllRead,
                         (Func_t)String_FileAllWrite,
                         (Func_t)String_Print,
                         (Func_t)String_PrintErr,
                         (Func_t)String_PrintLine,
                         (Func_t)String_ToString_Bool,
                         (Func_t)String_ToString_Decimal,
                         (Func_t)String_ToString_Decimal_Unsigned,
                         (Func_t)String_ToString_Digit,
                         (Func_t)String_ToString_StringAry,
                         (Func_t)String_ValueOf_Bool,
                         (Func_t)String_ValueOf_Decimal,
                         (Func_t)String_ValueOf_Decimal_Unsigned,
                         (Func_t)String_ValueOf_Digit,
                         (Func_t)StringAry_Constructor,
                         (Func_t)StringAry_Destructor,
                         (Func_t)StringAry_Get,
                         (Func_t)StringAry_Insert,
                         (Func_t)StringAry_Remove,
                         (Func_t)StringAry_Push,
                         (Func_t)StringAry_Pop,
                         (Func_t)StringAry_Search,
                         (Func_t)StringAry_Contains,
                         (Func_t)StringAry_toAry,
                         (Func_t)StringAry_toList,
                         (Func_t)StringAry_isAry,
                         (Func_t)StringAry_isList,
                         (Func_t)StringAry_Foreach,
                         (Func_t)StringAry_CountIf };

  return 0;
}
