
#include <Json.h>
#include <Object.h>
#include <String.h>
#include <StringAry.h>
#include <Types/DataType.h>

// clang-format off

/*
  DataTypeName      : 데이터 타입 이름
  DataTypeCode      : 데이터 타입 코드
  DataType_WordSize : 데이터 크기
  Policy            : 데이터의 기본 정책
  Constructor       : 기본 생성자 - void (*)(void **This)
  Destructor        : 기본 소멸자 - void (*)(void *This)
  Boxing            : 오브젝트 - 박싱을 위한 함수
  UnBoxing          : 오브젝트 - 언박싱을 위한 함수
*/

const DataTypeInfo_t g_DataTypeTable[] = {
//  DataTypeName            | DataTypeCode                    | DataType_WordSize           | Policy      | Constructor                           | Destructor                              | Boxing                                            | UnBoxing 
  { "char",                   DataType_Char,                    sizeof(char),                 0,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Char,                       (Func_t)__Object_UnBoxing_Char },
  { "unsigned char",          DataType_U_Char,                  sizeof(unsigned char),        0 | 4,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_U_Char,                     (Func_t)__Object_UnBoxing_U_Char },
  { "short",                  DataType_Short,                   sizeof(short),                0,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Short,                      (Func_t)__Object_UnBoxing_Short },
  { "unsigned short",         DataType_U_Short,                 sizeof(unsigned short),       0 | 4,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_U_Short,                    (Func_t)__Object_UnBoxing_U_Short },
  { "int",                    DataType_Int,                     sizeof(int),                  0,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Int,                        (Func_t)__Object_UnBoxing_Int },
  { "unsigned int",           DataType_U_Int,                   sizeof(unsigned int),         0 | 4,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_U_Int,                      (Func_t)__Object_UnBoxing_U_Int },
  { "long",                   DataType_Long,                    sizeof(long),                 0,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Long,                       (Func_t)__Object_UnBoxing_Long },
  { "unsigned long",          DataType_U_Long,                  sizeof(unsigned long),        0 | 4,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_U_Long,                     (Func_t)__Object_UnBoxing_U_Long },
  { "long long",              DataType_Long_Long,               sizeof(long long),            0,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_LongLong,                   (Func_t)__Object_UnBoxing_LongLong },
  { "unsigned long long",     DataType_U_Long_Long,             sizeof(unsigned long long),   0 | 4,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_U_LongLong,                 (Func_t)__Object_UnBoxing_U_LongLong },
  { "float",                  DataType_Float,                   sizeof(float),                1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Float,                      (Func_t)__Object_UnBoxing_Float },
  { "double",                 DataType_Double,                  sizeof(double),               1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Double,                     (Func_t)__Object_UnBoxing_Double },
  { "char*",                  DataType_Ptr_Char,                sizeof(void *),               1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Ptr_Char,                   (Func_t)__Object_UnBoxing_Ptr_Char },
  { "char**",                 DataType_Double_Ptr_Char,         sizeof(void *),               1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Double_Ptr_Char,            (Func_t)__Object_UnBoxing_Double_Ptr_Char },
  { "unsigned char*",         DataType_Ptr_U_Char,              sizeof(void *),               1 | 4,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Ptr_U_Char,                 (Func_t)__Object_UnBoxing_Ptr_U_Char },
  { "unsigned char**",        DataType_Double_Ptr_U_Char,       sizeof(void *),               1 | 4,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Double_Ptr_U_Char,          (Func_t)__Object_UnBoxing_Double_Ptr_U_Char },
  { "short*",                 DataType_Ptr_Short,               sizeof(void *),               1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Ptr_Short,                  (Func_t)__Object_UnBoxing_Ptr_Short },
  { "short**",                DataType_Double_Ptr_Short,        sizeof(void *),               1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Double_Ptr_Short,           (Func_t)__Object_UnBoxing_Double_Ptr_Short },
  { "unsigned short*",        DataType_Ptr_U_Short,             sizeof(void *),               1 | 4,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Ptr_U_Short,                (Func_t)__Object_UnBoxing_Ptr_U_Short },
  { "unsigned short**",       DataType_Double_Ptr_U_Short,      sizeof(void *),               1 | 4,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Double_Ptr_U_Short,         (Func_t)__Object_UnBoxing_Double_Ptr_U_Short },
  { "int*",                   DataType_Ptr_Int,                 sizeof(void *),               1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Ptr_Int,                    (Func_t)__Object_UnBoxing_Ptr_Int },
  { "int**",                  DataType_Double_Ptr_Int,          sizeof(void *),               1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Double_Ptr_Int,             (Func_t)__Object_UnBoxing_Double_Ptr_Int },
  { "unsigned int*",          DataType_Ptr_U_Int,               sizeof(void *),               1 | 4,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Ptr_U_Int,                  (Func_t)__Object_UnBoxing_Ptr_U_Int },
  { "unsigned int**",         DataType_Double_Ptr_U_Int,        sizeof(void *),               1 | 4,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Double_Ptr_U_Int,           (Func_t)__Object_UnBoxing_Double_Ptr_U_Int },
  { "long*",                  DataType_Ptr_Long,                sizeof(void *),               1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Ptr_Long,                   (Func_t)__Object_UnBoxing_Ptr_Long },
  { "long**",                 DataType_Double_Ptr_Long,         sizeof(void *),               1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Double_Ptr_Long,            (Func_t)__Object_UnBoxing_Double_Ptr_Long },
  { "unsigned long*",         DataType_Ptr_U_Long,              sizeof(void *),               1 | 4,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Ptr_U_Long,                 (Func_t)__Object_UnBoxing_Ptr_U_Long },
  { "unsigned long**",        DataType_Double_Ptr_U_Long,       sizeof(void *),               1 | 4,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Double_Ptr_U_Long,          (Func_t)__Object_UnBoxing_Double_Ptr_U_Long },
  { "long long*",             DataType_Ptr_Long_Long,           sizeof(void *),               1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Ptr_Long_Long,              (Func_t)__Object_UnBoxing_Ptr_Long_Long },
  { "long long**",            DataType_Double_Ptr_Long_Long,    sizeof(void *),               1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Double_Ptr_Long_Long,       (Func_t)__Object_UnBoxing_Double_Ptr_Long_Long },
  { "unsigned long long*",    DataType_Ptr_U_Long_Long,         sizeof(void *),               1 | 4,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Ptr_U_Long_Long,            (Func_t)__Object_UnBoxing_Ptr_U_Long_Long },
  { "unsigned long long**",   DataType_Double_Ptr_U_Long_Long,  sizeof(void *),               1 | 4,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Double_Ptr_U_Long_Long,     (Func_t)__Object_UnBoxing_Double_Ptr_U_Long_Long },
  { "float*",                 DataType_Ptr_Float,               sizeof(void *),               1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Ptr_Float,                  (Func_t)__Object_UnBoxing_Ptr_Float },
  { "float**",                DataType_Double_Ptr_Float,        sizeof(void *),               1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Double_Ptr_Float,           (Func_t)__Object_UnBoxing_Double_Ptr_Float },
  { "double*",                DataType_Ptr_Double,              sizeof(void *),               1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Ptr_Double,                 (Func_t)__Object_UnBoxing_Ptr_Double },
  { "double**",               DataType_Double_Ptr_Double,       sizeof(void *),               1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Double_Ptr_Double,          (Func_t)__Object_UnBoxing_Double_Ptr_Double },
  { "void*",                  DataType_Ptr_Void,                sizeof(void *),               1 | 8,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Ptr_Void,                   (Func_t)__Object_UnBoxing_Ptr_Void },
  { "void**",                 DataType_Double_Ptr_Void,         sizeof(void *),               1 | 8,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Double_Ptr_Void,            (Func_t)__Object_UnBoxing_Double_Ptr_Void },
  { "void***",                DataType_Triple_Ptr_Void,         sizeof(void *),               1 | 8,        NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Triple_Ptr_Void,            (Func_t)__Object_UnBoxing_Triple_Ptr_Void },
  { "bool",                   DataType_Bool,                    sizeof(bool),                 0,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Bool,                       (Func_t)__Object_UnBoxing_Bool },
  { "bool*",                  DataType_Ptr_Bool,                sizeof(void *),               1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Ptr_Bool,                   (Func_t)__Object_UnBoxing_Ptr_Bool },
  { "bool**",                 DataType_Double_Ptr_Bool,         sizeof(void *),               1,            NULL,                                   NULL,                                     (Func_t)__Object_Boxing_Double_Ptr_Bool,            (Func_t)__Object_UnBoxing_Double_Ptr_Bool },
  { "String",                 DataType_String,                  sizeof(void *),               1,            (Constructor_t) String_Constructor_Wcs, (Destructor_t) String_Destructor,         (Func_t)__Object_Boxing_String,                     (Func_t)__Object_UnBoxing_String },
  { "StringAry",              DataType_StringAry,               sizeof(void *),               1,            (Constructor_t) StringAry_Constructor,  (Destructor_t) StringAry_Destructor,      (Func_t)__Object_Boxing_StringAry,                  (Func_t)__Object_UnBoxing_StringAry },
  { "JSONObject",             DataType_JSONObject,              sizeof(void *),               1,            (Constructor_t) JSON_Constructor,       (Destructor_t) JSON_Destructor,           (Func_t)__Object_Boxing_JSONObject,                 (Func_t)__Object_UnBoxing_JSONObject },
  { "Unknown",                DataType_None,                    0,                            0,            NULL,                                   NULL,                                     NULL,                                               NULL},
};