
#include <nString.h>

struct nString_Method StringMethod[] = { nString_Constructor_Chs,
                                         nString_Constructor_Wcs,
                                         nString_Constructor_Str,
                                         nString_Constructor_Strp,
                                         nString_Destructor,
                                         nString_Join,
                                         nString_Append,
                                         nString_Loop,
                                         nString_Compare,
                                         nString_Trim,
                                         nString_Length,
                                         nString_get,
                                         nString_set,
                                         nString_Left,
                                         nString_Right,
                                         nString_Middle,
                                         nString_Extract,
                                         nString_Reverse,
                                         nString_ToLower,
                                         nString_ToUpper,
                                         nString_Contains,
                                         nString_Count,
                                         nString_IndexOf,
                                         nString_IndexAt,
                                         nString_IndexFor,
                                         nString_LastOfIndex,
                                         nString_Replace,
                                         nString_ReplaceAt,
                                         nString_ReplaceAll,
                                         nString_Split,
                                         nString_SubString,
                                         nString_Pattern,
                                         nString_isAlpha,
                                         nString_isLower,
                                         nString_isUpper,
                                         nString_isDecimal,
                                         nString_isDigit,
                                         nString_isSpace,
                                         nString_isAlphaDigit,
                                         nString_isHex,
                                         nString_isControl,
                                         nString_isOctal,
                                         nString_isBinary,
                                         nString_Check,
                                         nString_Format,
                                         nString_Notation,
                                         nString_FileAllRead,
                                         nString_FileAllWrite,
                                         nString_UTF8Decoder,
                                         nString_UTF8Encoder };
struct nStringAry_Method StringAryMethod[] = {
  nStringAry_Constructor, nStringAry_Destructor, nStringAry_Clear,
  nStringAry_get,         nStringAry_set,        nStringAry_Insert,
  nStringAry_Remove,      nStringAry_Push,       nStringAry_Pop,
  nStringAry_Search,      nStringAry_Contains,   nStringAry_toAry,
  nStringAry_toList,      nStringAry_Type,       nStringAry_CountIf,
  nStringAry_Length
};
struct nRegExp_Method RegExpMethod[] = {
  nRegExp_Constructor_Str, nRegExp_Constructor_Clone,
  nRegExp_Destructor,      nRegExp_Analysis,
  nRegExp_Count,           nRegExp_IndexOf,
  nRegExp_IndexAt,         nRegExp_IndexFor,
  nRegExp_IndexAll,        nRegExp_LastOfIndex,
  nRegExp_Replace,         nRegExp_ReplaceAt,
  nRegExp_ReplaceAll,      nRegExp_Split,
  nRegExp_SubString
};
struct nChs_Method ChsMethod[] = {
  nChs_ChsLen,    nChs_WcsLen,  nChs_IsAlpha,  nChs_IsLower,      nChs_IsUpper,
  nChs_IsDecimal, nChs_IsDigit, nChs_IsSpace,  nChs_IsAlphaDigit, nChs_IsHex,
  nChs_IsControl, nChs_IsOctal, nChs_IsBinary, nChs_ToLower,      nChs_ToUpper
};