# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Cmake

# Include any dependencies generated for this target.
include CMakeFiles/../Excute/Qi.out.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/../Excute/Qi.out.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/../Excute/Qi.out.dir/flags.make

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi.cpp.o: CMakeFiles/../Excute/Qi.out.dir/flags.make
CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi.cpp.o: /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Cmake/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi.cpp.o -c /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi.cpp

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi.cpp > CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi.cpp.i

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi.cpp -o CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi.cpp.s

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_pars.cpp.o: CMakeFiles/../Excute/Qi.out.dir/flags.make
CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_pars.cpp.o: /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_pars.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Cmake/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_pars.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_pars.cpp.o -c /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_pars.cpp

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_pars.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_pars.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_pars.cpp > CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_pars.cpp.i

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_pars.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_pars.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_pars.cpp -o CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_pars.cpp.s

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tkn.cpp.o: CMakeFiles/../Excute/Qi.out.dir/flags.make
CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tkn.cpp.o: /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tkn.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Cmake/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tkn.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tkn.cpp.o -c /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tkn.cpp

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tkn.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tkn.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tkn.cpp > CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tkn.cpp.i

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tkn.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tkn.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tkn.cpp -o CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tkn.cpp.s

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tbl.cpp.o: CMakeFiles/../Excute/Qi.out.dir/flags.make
CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tbl.cpp.o: /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tbl.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Cmake/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tbl.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tbl.cpp.o -c /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tbl.cpp

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tbl.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tbl.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tbl.cpp > CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tbl.cpp.i

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tbl.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tbl.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tbl.cpp -o CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tbl.cpp.s

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_code.cpp.o: CMakeFiles/../Excute/Qi.out.dir/flags.make
CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_code.cpp.o: /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_code.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Cmake/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_code.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_code.cpp.o -c /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_code.cpp

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_code.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_code.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_code.cpp > CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_code.cpp.i

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_code.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_code.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_code.cpp -o CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_code.cpp.s

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_misc.cpp.o: CMakeFiles/../Excute/Qi.out.dir/flags.make
CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_misc.cpp.o: /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_misc.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Cmake/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building CXX object CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_misc.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_misc.cpp.o -c /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_misc.cpp

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_misc.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_misc.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_misc.cpp > CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_misc.cpp.i

CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_misc.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_misc.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_misc.cpp -o CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_misc.cpp.s

# Object files for target ../Excute/Qi.out
__/Excute/Qi_out_OBJECTS = \
"CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi.cpp.o" \
"CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_pars.cpp.o" \
"CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tkn.cpp.o" \
"CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tbl.cpp.o" \
"CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_code.cpp.o" \
"CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_misc.cpp.o"

# External object files for target ../Excute/Qi.out
__/Excute/Qi_out_EXTERNAL_OBJECTS =

../Excute/Qi.out: CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi.cpp.o
../Excute/Qi.out: CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_pars.cpp.o
../Excute/Qi.out: CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tkn.cpp.o
../Excute/Qi.out: CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_tbl.cpp.o
../Excute/Qi.out: CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_code.cpp.o
../Excute/Qi.out: CMakeFiles/../Excute/Qi.out.dir/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Qi_misc.cpp.o
../Excute/Qi.out: CMakeFiles/../Excute/Qi.out.dir/build.make
../Excute/Qi.out: CMakeFiles/../Excute/Qi.out.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Cmake/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Linking CXX executable ../Excute/Qi.out"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/../Excute/Qi.out.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/../Excute/Qi.out.dir/build: ../Excute/Qi.out

.PHONY : CMakeFiles/../Excute/Qi.out.dir/build

CMakeFiles/../Excute/Qi.out.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/../Excute/Qi.out.dir/cmake_clean.cmake
.PHONY : CMakeFiles/../Excute/Qi.out.dir/clean

CMakeFiles/../Excute/Qi.out.dir/depend:
	cd /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Cmake && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Cmake /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Cmake /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Cmake /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Cmake /home/nugunga/Desktop/AnyangTechInterpreter/interpreter/Cmake/Excute/Qi.out.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/../Excute/Qi.out.dir/depend

