add_executable(kern_tests
    support/ArenaTest.cpp
    support/DiagnosticTest.cpp
    lexer/LexerTest.cpp
    parser/ParserTest.cpp
    sema/SemaTest.cpp
    sema/PurityTest.cpp
    ir/IRTest.cpp
    codegen/CodeGenTest.cpp
    hir/HIRTest.cpp
    hir/HIRBuilderTest.cpp
    hir/HIRPassesTest.cpp
    lir/LIRTest.cpp
    lir/LIRBuilderTest.cpp
)
target_link_libraries(kern_tests
    kern_lir
    kern_hir
    kern_codegen
    kern_ir
    kern_sema
    kern_parser
    kern_lexer
    kern_support
    GTest::gtest_main
)
include(GoogleTest)
gtest_discover_tests(kern_tests DISCOVERY_TIMEOUT 120 DISCOVERY_MODE PRE_TEST)
