#pragma once
#include "kern/support/SourceLocation.h"
#include "kern/support/TypeSystem.h"
#include <cstdint>
#include <string_view>
#include <vector>

namespace kern {

// Debug metadata generated by the compiler for use by kern-dbg.
// Populated by DebugInfoBuilder from MachIR + CompilationContext.

struct LocalVarInfo {
    std::string_view name;
    TypeId type = 0;
    int32_t stack_offset = 0;       // [rbp + offset]
    uint32_t scope_start_line = 0;
    uint32_t scope_end_line = 0;
};

struct FunctionDebugInfo {
    std::string_view name;
    SourceLocation source_loc;
    uint64_t code_start = 0;        // offset in .text section
    uint64_t code_end = 0;
    std::vector<LocalVarInfo> locals;
};

struct SourceMapping {
    uint64_t addr = 0;              // instruction offset
    uint32_t line = 0;
    uint32_t column = 0;
    std::string_view file;
};

struct DebugInfo {
    std::vector<FunctionDebugInfo> functions;
    std::vector<SourceMapping> source_map;  // sorted by addr

    // Lookup: find source location for a given address
    const SourceMapping* findMapping(uint64_t addr) const;

    // Lookup: find function containing an address
    const FunctionDebugInfo* findFunction(uint64_t addr) const;

    // Lookup: find local variable by name within a function
    const LocalVarInfo* findLocal(const FunctionDebugInfo& fn,
                                  std::string_view name) const;
};

} // namespace kern
